#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: C:/VCLOG/
#  file: C:/VCLOG/sell.log
#  level:
#    com.company.SellApplicationTests: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


server:
  port: 8080
  context-path: /sell

